GET http://localhost:9000/api/schemes

####

GET http://localhost:9000/api/schemes/1/steps

####

POST http://localhost:9000/api/schemes
Content-Type: application/json

{
    "scheme_name": "Shadow"
}

####

POST http://localhost:9000/api/schemes/1/steps
Content-Type: application/json

{
    "instructions": "Rachael",
    "step_number": 3
}